/**
 * Karrierevei-datasett med match-kriterier mot RIASEC-profil.
 *
 * fitScore beregnes fra RIASEC-overlap (0–100).
 * Bransje, utdanningsnivå og NAV-data (lønn, etterspørsel) er inkludert.
 */

import type { RiasecScores } from "@/types/domain";

export type EducationLevel =
  | "vgs"
  | "fagbrev"
  | "bachelor"
  | "master"
  | "phd";

export type Demand = "high" | "medium" | "low";

/** Automatiseringsrisiko fra AI (OECD-estimat) */
export type AiDisruptionRisk = "low" | "medium" | "high";

/** Veksttrend i arbeidsmarkedet */
export type GrowthTrend = "declining" | "stable" | "growing" | "booming";

export type CareerNode = {
  id: string;
  title: string;
  sector: string;
  educationLevel: EducationLevel;
  /** Primære RIASEC-koder som passer */
  riasecCodes: (keyof RiasecScores)[];
  /** Årslonn NOK (median) */
  medianSalary: number;
  demand: Demand;
  description: string;
  /** Typiske utdanningsveier */
  educationPaths: string[];
  /** Videreutvikling fra denne karrieren */
  advancesTo?: string[];
  /** AI-automatiseringsrisiko (#115) */
  aiDisruptionRisk: AiDisruptionRisk;
  /** Veksttrend i arbeidsmarkedet (#115) */
  growthTrend: GrowthTrend;
  /** Grønn/bærekraftig karriere (#115) */
  sustainability: boolean;
  /** Work-life balance (1–5, der 5 er best) (#115) */
  workLifeBalance: 1 | 2 | 3 | 4 | 5;
};

export const CAREER_NODES: CareerNode[] = [
  // ─── Teknologi & Data ─────────────────────────────────────────────────────
  {
    id: "software-engineer",
    title: "Programvareutvikler",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 720000,
    demand: "high",
    description: "Utvikler programvare, applikasjoner og systemer. Høy etterspørsel i alle bransjer.",
    educationPaths: ["Informatikk (bachelor/master)", "Datateknikk (sivilingeniør)"],
    advancesTo: ["tech-lead", "cto", "data-scientist"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "data-scientist",
    title: "Datavitenskap / ML-ingeniør",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "conventional", "realistic"],
    medianSalary: 780000,
    demand: "high",
    description: "Analyserer store datamengder og bygger maskinlæringsmodeller.",
    educationPaths: ["Datavitenskap (master)", "Matematikk + informatikk", "Statistikk"],
    advancesTo: ["ai-researcher", "tech-lead"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "ux-designer",
    title: "UX/UI-designer",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "investigative", "social"],
    medianSalary: 650000,
    demand: "high",
    description: "Designer brukeropplevelser og grensesnitt for digitale produkter.",
    educationPaths: ["Interaksjonsdesign", "Grafisk design + UX", "Industridesign"],
    advancesTo: ["creative-director"],
    aiDisruptionRisk: "medium",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "cybersecurity",
    title: "Informasjonssikkerhet",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 730000,
    demand: "high",
    description: "Sikrer organisasjoner mot digitale trusler og angrep.",
    educationPaths: ["Informasjonssikkerhet (bachelor/master)", "Datateknikk"],
    advancesTo: ["ciso", "tech-lead"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "tech-lead",
    title: "Tech Lead / Arkitekt",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "enterprising", "realistic"],
    medianSalary: 900000,
    demand: "high",
    description: "Leder tekniske team og tar arkitekturbeslutninger.",
    educationPaths: ["Erfaring + master i informatikk"],
    advancesTo: ["cto"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "cto",
    title: "CTO / Teknologidirektør",
    sector: "Ledelse",
    educationLevel: "master",
    riasecCodes: ["enterprising", "investigative", "conventional"],
    medianSalary: 1200000,
    demand: "medium",
    description: "Ansvarlig for teknologistrategi i en organisasjon.",
    educationPaths: ["Master + ledererfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  // ─── Helse ────────────────────────────────────────────────────────────────
  {
    id: "lege",
    title: "Lege",
    sector: "Helse",
    educationLevel: "phd",
    riasecCodes: ["investigative", "social", "realistic"],
    medianSalary: 950000,
    demand: "high",
    description: "Diagnostiserer og behandler sykdommer. Lang og krevende utdanning.",
    educationPaths: ["Medisin (6 år)", "Turnustjeneste", "Spesialisering"],
    advancesTo: ["overlege", "forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "sykepleier",
    title: "Sykepleier",
    sector: "Helse",
    educationLevel: "bachelor",
    riasecCodes: ["social", "realistic", "investigative"],
    medianSalary: 580000,
    demand: "high",
    description: "Yter sykepleie og omsorg for pasienter i ulike settinger.",
    educationPaths: ["Sykepleie (bachelor, 3 år)"],
    advancesTo: ["spesialsykepleier", "avdelingsleder"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "psykolog",
    title: "Psykolog",
    sector: "Helse",
    educationLevel: "master",
    riasecCodes: ["social", "investigative", "artistic"],
    medianSalary: 750000,
    demand: "high",
    description: "Utforsker og behandler psykiske lidelser og utfordringer.",
    educationPaths: ["Profesjonsstudium i psykologi (6 år)"],
    advancesTo: ["spesialistpsykolog", "forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "fysioterapeut",
    title: "Fysioterapeut",
    sector: "Helse",
    educationLevel: "bachelor",
    riasecCodes: ["social", "realistic", "investigative"],
    medianSalary: 560000,
    demand: "high",
    description: "Behandler bevegelsesrelaterte lidelser og rehabiliterer pasienter.",
    educationPaths: ["Fysioterapi (bachelor, 3 år)"],
    advancesTo: ["spesialistfysioterapeut"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  // ─── Utdanning ────────────────────────────────────────────────────────────
  {
    id: "laerer",
    title: "Lærer (grunnskole/VGS)",
    sector: "Utdanning",
    educationLevel: "master",
    riasecCodes: ["social", "artistic", "conventional"],
    medianSalary: 580000,
    demand: "high",
    description: "Underviser og veileder elever i grunn- og videregående skole.",
    educationPaths: ["Grunnskolelærer (5 år)", "Lektor (5 år)"],
    advancesTo: ["rektor"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "barnehage-laerer",
    title: "Barnehagelærer",
    sector: "Utdanning",
    educationLevel: "bachelor",
    riasecCodes: ["social", "artistic", "realistic"],
    medianSalary: 510000,
    demand: "high",
    description: "Planlegger og leder pedagogisk arbeid med barn under skolealder.",
    educationPaths: ["Barnehagelærer (bachelor, 3 år)"],
    advancesTo: ["styrer"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "universitetslektor",
    title: "Universitetslektor / Forsker",
    sector: "Utdanning",
    educationLevel: "phd",
    riasecCodes: ["investigative", "social", "artistic"],
    medianSalary: 680000,
    demand: "medium",
    description: "Underviser og forsker ved høyere utdanningsinstitusjoner.",
    educationPaths: ["Master + PhD"],
    advancesTo: ["professor"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 4,
  },
  // ─── Økonomi & Forretning ─────────────────────────────────────────────────
  {
    id: "revisor",
    title: "Revisor",
    sector: "Økonomi",
    educationLevel: "master",
    riasecCodes: ["conventional", "investigative", "enterprising"],
    medianSalary: 680000,
    demand: "medium",
    description: "Kontrollerer regnskap og gir råd om finansiell risiko.",
    educationPaths: ["Revisjon/regnskap (master)", "Autorisert revisor"],
    aiDisruptionRisk: "high",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "oekonom",
    title: "Økonom / Finansanalytiker",
    sector: "Økonomi",
    educationLevel: "master",
    riasecCodes: ["conventional", "investigative", "enterprising"],
    medianSalary: 720000,
    demand: "medium",
    description: "Analyserer finansielle data og gir investeringsråd.",
    educationPaths: ["Siviløkonom (NHH/BI)", "Økonomi og administrasjon"],
    advancesTo: ["cfo"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "entrepreneur",
    title: "Gründer / Entrepenør",
    sector: "Forretning",
    educationLevel: "bachelor",
    riasecCodes: ["enterprising", "artistic", "investigative"],
    medianSalary: 600000,
    demand: "medium",
    description: "Bygger og leder egne virksomheter fra idé til marked.",
    educationPaths: ["Varierende — bachelor i økonomi, teknologi eller relevant felt"],
    advancesTo: ["ceo"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "marknadsforer",
    title: "Markedsfører / Kommunikasjonsrådgiver",
    sector: "Forretning",
    educationLevel: "bachelor",
    riasecCodes: ["enterprising", "artistic", "social"],
    medianSalary: 590000,
    demand: "medium",
    description: "Utformer kommunikasjonsstrategier og markedskampanjer.",
    educationPaths: ["Markedsføring/kommunikasjon (bachelor)"],
    advancesTo: ["cmo"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  // ─── Kreative fag ─────────────────────────────────────────────────────────
  {
    id: "arkitekt",
    title: "Arkitekt",
    sector: "Kreativ",
    educationLevel: "master",
    riasecCodes: ["artistic", "realistic", "investigative"],
    medianSalary: 680000,
    demand: "medium",
    description: "Designer bygninger og byrom med fokus på estetikk og funksjon.",
    educationPaths: ["Arkitektur (master, 5 år) — NTNU, AHO"],
    advancesTo: ["byplanlegger"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "grafisk-designer",
    title: "Grafisk designer",
    sector: "Kreativ",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "realistic", "conventional"],
    medianSalary: 530000,
    demand: "medium",
    description: "Skaper visuell kommunikasjon for trykk og digitale flater.",
    educationPaths: ["Grafisk design (bachelor)", "Visuell kommunikasjon"],
    advancesTo: ["art-director", "ux-designer"],
    aiDisruptionRisk: "high",
    growthTrend: "declining",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "journalist",
    title: "Journalist",
    sector: "Kreativ",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "social", "enterprising"],
    medianSalary: 560000,
    demand: "low",
    description: "Undersøker og formidler nyheter og reportasjer.",
    educationPaths: ["Journalistikk (bachelor)"],
    advancesTo: ["redaktoer"],
    aiDisruptionRisk: "high",
    growthTrend: "declining",
    sustainability: false,
    workLifeBalance: 3,
  },
  // ─── Ingeniør & Naturvitenskap ─────────────────────────────────────────────
  {
    id: "sivilingenioer",
    title: "Sivilingeniør",
    sector: "Ingeniør",
    educationLevel: "master",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 780000,
    demand: "high",
    description: "Løser tekniske problemer innen bygg, maskin, elektro eller kjemi.",
    educationPaths: ["Sivilingeniør (5 år) — NTNU, UiB, UiO"],
    advancesTo: ["prosjektleder", "tech-lead", "forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "biolog",
    title: "Biolog / Bioteknolog",
    sector: "Naturvitenskap",
    educationLevel: "master",
    riasecCodes: ["investigative", "realistic", "social"],
    medianSalary: 620000,
    demand: "medium",
    description: "Forsker på levende organismer og biologiske prosesser.",
    educationPaths: ["Biologi (master)", "Bioteknologi (master)"],
    advancesTo: ["forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: true,
    workLifeBalance: 4,
  },
  // ─── Sosial & Offentlig sektor ─────────────────────────────────────────────
  {
    id: "jurist",
    title: "Advokat / Jurist",
    sector: "Juss",
    educationLevel: "master",
    riasecCodes: ["enterprising", "investigative", "conventional"],
    medianSalary: 830000,
    demand: "medium",
    description: "Rådgir klienter og representerer dem i rettslige saker.",
    educationPaths: ["Rettsvitenskap (master, 5 år)"],
    advancesTo: ["partner-advokatfirma"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "sosialarbeider",
    title: "Sosionom / Sosialt arbeid",
    sector: "Sosial",
    educationLevel: "bachelor",
    riasecCodes: ["social", "conventional", "artistic"],
    medianSalary: 520000,
    demand: "high",
    description: "Hjelper individer og familier med sosiale og psykiske utfordringer.",
    educationPaths: ["Sosialt arbeid (bachelor, 3 år)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "politi",
    title: "Politibetjent",
    sector: "Offentlig",
    educationLevel: "bachelor",
    riasecCodes: ["realistic", "social", "enterprising"],
    medianSalary: 560000,
    demand: "medium",
    description: "Opretholder lov og orden, forebygger kriminalitet.",
    educationPaths: ["Politihøgskolen (bachelor, 3 år)"],
    advancesTo: ["etterforsker"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "forsker",
    title: "Forsker / Akademiker",
    sector: "Akademia",
    educationLevel: "phd",
    riasecCodes: ["investigative", "artistic", "conventional"],
    medianSalary: 680000,
    demand: "medium",
    description: "Driver grunnforskning og publiserer vitenskapelige arbeider.",
    educationPaths: ["Master + PhD (3–4 år)"],
    advancesTo: ["professor"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  // ─── Handel & Service ─────────────────────────────────────────────────────
  {
    id: "laege-spesialist",
    title: "Spesiallege",
    sector: "Helse",
    educationLevel: "phd",
    riasecCodes: ["investigative", "realistic", "social"],
    medianSalary: 1150000,
    demand: "high",
    description: "Spesialist innen f.eks. kirurgi, onkologi eller indremedisin.",
    educationPaths: ["Medisin + spesialiseringsutdanning (5–7 år)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "produkt-manager",
    title: "Produktleder (Product Manager)",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["enterprising", "investigative", "social"],
    medianSalary: 780000,
    demand: "high",
    description: "Leder utviklingen av digitale produkter fra strategi til lansering.",
    educationPaths: ["Variert bakgrunn — teknologi, økonomi, design"],
    advancesTo: ["cpo", "ceo"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "laerer-spesialpedagog",
    title: "Spesialpedagog",
    sector: "Utdanning",
    educationLevel: "master",
    riasecCodes: ["social", "investigative", "artistic"],
    medianSalary: 610000,
    demand: "high",
    description: "Tilpasser opplæring for elever med spesielle behov.",
    educationPaths: ["Spesialpedagogikk (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },

  // ─── Energiomstilling & Bærekraft (#115) ─────────────────────────────────
  {
    id: "energiingenior",
    title: "Energiingeniør",
    sector: "Energi",
    educationLevel: "master",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 750000,
    demand: "high",
    description: "Planlegger og optimaliserer energisystemer — sol, vind, hydrogen og kraftnett.",
    educationPaths: ["Energi og miljøfysikk (master)", "Fornybar energi (NTNU, UiS)"],
    advancesTo: ["prosjektleder"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "barekraftskonsulent",
    title: "Bærekraftskonsulent (ESG)",
    sector: "Bærekraft",
    educationLevel: "master",
    riasecCodes: ["investigative", "social", "conventional"],
    medianSalary: 680000,
    demand: "high",
    description: "Rådgir bedrifter om ESG-rapportering, klimarisiko og bærekraftig omstilling.",
    educationPaths: ["Økonomi/miljø (master) + ESG-sertifisering", "Industriell økologi (NTNU)"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 4,
  },
  {
    id: "vindkrafttekniker",
    title: "Vindkrafttekniker",
    sector: "Energi",
    educationLevel: "fagbrev",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 560000,
    demand: "high",
    description: "Installerer, drifter og vedlikeholder vindturbiner — offshore og onshore.",
    educationPaths: ["Elektro/mekanisk fagbrev + spesialisering", "Vindenergi (fagskole)"],
    advancesTo: ["energiingenior"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "hydrogeningenior",
    title: "Hydrogeningeniør",
    sector: "Energi",
    educationLevel: "master",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 780000,
    demand: "high",
    description: "Utvikler hydrogen-produksjon, lagring og distribusjon for grønn omstilling.",
    educationPaths: ["Kjemiteknikk (master)", "Energiteknologi (NTNU, UiS)"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "miljoradgiver",
    title: "Miljørådgiver",
    sector: "Bærekraft",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "social", "realistic"],
    medianSalary: 590000,
    demand: "high",
    description: "Kartlegger miljøpåvirkning, lager konsekvensutredninger og sikrer miljøkrav.",
    educationPaths: ["Miljøvitenskap (bachelor)", "Naturforvaltning (bachelor)"],
    advancesTo: ["barekraftskonsulent"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: true,
    workLifeBalance: 4,
  },
  {
    id: "sirkulaerokonomi",
    title: "Spesialist sirkulær økonomi",
    sector: "Bærekraft",
    educationLevel: "master",
    riasecCodes: ["investigative", "enterprising", "conventional"],
    medianSalary: 700000,
    demand: "high",
    description: "Designer forretningsmodeller for gjenbruk, reparasjon og ressursoptimalisering.",
    educationPaths: ["Industriell økologi (master)", "Innovasjon og bærekraft (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 4,
  },

  // ─── AI / Maskinlæring (#115) ──────────────────────────────────────────
  {
    id: "ml-engineer",
    title: "ML-ingeniør",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 820000,
    demand: "high",
    description: "Bygger og deployer maskinlæringsmodeller i produksjon — MLOps og modelloptimalisering.",
    educationPaths: ["Informatikk/ML (master)", "Datavitenskap + MLOps-erfaring"],
    advancesTo: ["ai-researcher"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "ai-etiker",
    title: "AI-etiker / Ansvarlig AI",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "social", "artistic"],
    medianSalary: 700000,
    demand: "high",
    description: "Sikrer at AI-systemer er rettferdige, transparente og i tråd med EU AI Act.",
    educationPaths: ["Filosofi/juss + teknologi (tverrfaglig)", "AI-etikk (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "nlp-engineer",
    title: "NLP-ingeniør (språkteknologi)",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "realistic", "artistic"],
    medianSalary: 800000,
    demand: "high",
    description: "Utvikler språkmodeller, chatboter og tekstanalyse-systemer.",
    educationPaths: ["Datalingvistikk (master)", "Informatikk med NLP-spesialisering"],
    advancesTo: ["ai-researcher"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "robotikkingenior",
    title: "Robotikkingeniør",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 760000,
    demand: "high",
    description: "Designer og programmerer robotsystemer for industri, helse og logistikk.",
    educationPaths: ["Kybernetikk (master)", "Robotikk og AI (NTNU)"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 3,
  },

  // ─── Ny sektor: Helse & teknologi (#115) ──────────────────────────────
  {
    id: "helseinformatiker",
    title: "Helseinformatiker",
    sector: "Helse",
    educationLevel: "master",
    riasecCodes: ["investigative", "conventional", "social"],
    medianSalary: 680000,
    demand: "high",
    description: "Kobler helse og IT — utvikler journalsystemer, analyseverktøy og e-helseløsninger.",
    educationPaths: ["Helseinformatikk (master)", "Informatikk + helsefag"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "bioinformatiker",
    title: "Bioinformatiker",
    sector: "Naturvitenskap",
    educationLevel: "master",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 700000,
    demand: "high",
    description: "Analyserer biologisk data med informatikkverktøy — genomikk, proteomikk, legemiddeldesign.",
    educationPaths: ["Bioinformatikk (master)", "Biologi + informatikk"],
    advancesTo: ["forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },

  // ─── Avanserte noder (branching-mål) ──────────────────────────────────────
  {
    id: "ai-researcher",
    title: "AI-forsker",
    sector: "Teknologi",
    educationLevel: "phd",
    riasecCodes: ["investigative", "conventional", "realistic"],
    medianSalary: 950000,
    demand: "high",
    description: "Forsker på kunstig intelligens, maskinlæring og nevrale nettverk.",
    educationPaths: ["Master + PhD i informatikk/maskinlæring"],
    advancesTo: ["forsker"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "creative-director",
    title: "Kreativ leder",
    sector: "Kreativ",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "enterprising", "social"],
    medianSalary: 780000,
    demand: "medium",
    description: "Leder kreative team og setter visuell og konseptuell retning.",
    educationPaths: ["Design (bachelor) + erfaring"],
    advancesTo: ["cmo"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "ciso",
    title: "CISO / IT-sikkerhetssjef",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["investigative", "enterprising", "conventional"],
    medianSalary: 1050000,
    demand: "high",
    description: "Overordnet ansvar for informasjonssikkerhet i organisasjonen.",
    educationPaths: ["Informasjonssikkerhet (master) + erfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "overlege",
    title: "Overlege / Avdelingssjef",
    sector: "Helse",
    educationLevel: "phd",
    riasecCodes: ["investigative", "social", "enterprising"],
    medianSalary: 1200000,
    demand: "high",
    description: "Leder medisinsk avdeling og har overordnet faglig ansvar.",
    educationPaths: ["Medisin + spesialisering + ledererfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "spesialsykepleier",
    title: "Spesialsykepleier",
    sector: "Helse",
    educationLevel: "master",
    riasecCodes: ["social", "realistic", "investigative"],
    medianSalary: 680000,
    demand: "high",
    description: "Spesialisert sykepleier innen f.eks. intensiv, anestesi eller kreft.",
    educationPaths: ["Sykepleie + videreutdanning (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "avdelingsleder",
    title: "Avdelingsleder (helse)",
    sector: "Helse",
    educationLevel: "master",
    riasecCodes: ["enterprising", "social", "conventional"],
    medianSalary: 720000,
    demand: "medium",
    description: "Leder en helsefaglig avdeling med personal- og budsjettansvar.",
    educationPaths: ["Helsefag + ledelse (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "spesialistpsykolog",
    title: "Spesialistpsykolog",
    sector: "Helse",
    educationLevel: "phd",
    riasecCodes: ["social", "investigative", "artistic"],
    medianSalary: 900000,
    demand: "high",
    description: "Godkjent spesialist i klinisk psykologi, nevropsykologi eller andre retninger.",
    educationPaths: ["Psykologi (profesjon) + spesialistutdanning (5 år)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "spesialistfysioterapeut",
    title: "Spesialistfysioterapeut",
    sector: "Helse",
    educationLevel: "master",
    riasecCodes: ["realistic", "social", "investigative"],
    medianSalary: 680000,
    demand: "medium",
    description: "Spesialist innen f.eks. idrettsfysioterapi, manuell terapi eller nevrologi.",
    educationPaths: ["Fysioterapi (bachelor) + spesialisering (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "rektor",
    title: "Rektor",
    sector: "Utdanning",
    educationLevel: "master",
    riasecCodes: ["enterprising", "social", "conventional"],
    medianSalary: 780000,
    demand: "medium",
    description: "Leder en skole med pedagogisk, administrativt og personalansvar.",
    educationPaths: ["Lærer + pedagogisk ledelse (master)"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "professor",
    title: "Professor",
    sector: "Akademia",
    educationLevel: "phd",
    riasecCodes: ["investigative", "social", "artistic"],
    medianSalary: 820000,
    demand: "low",
    description: "Høyeste vitenskapelige stilling ved universiteter og høgskoler.",
    educationPaths: ["PhD + postdok + forskererfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "styrer",
    title: "Styrer (barnehage)",
    sector: "Utdanning",
    educationLevel: "bachelor",
    riasecCodes: ["enterprising", "social", "conventional"],
    medianSalary: 600000,
    demand: "high",
    description: "Leder en barnehage med personal- og driftsansvar.",
    educationPaths: ["Barnehagelærer + ledererfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "cfo",
    title: "CFO / Finansdirektør",
    sector: "Ledelse",
    educationLevel: "master",
    riasecCodes: ["conventional", "enterprising", "investigative"],
    medianSalary: 1150000,
    demand: "medium",
    description: "Overordnet ansvar for organisasjonens økonomi og finansiell strategi.",
    educationPaths: ["Siviløkonom + erfaring som finansanalytiker"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "ceo",
    title: "Administrerende direktør (CEO)",
    sector: "Ledelse",
    educationLevel: "master",
    riasecCodes: ["enterprising", "conventional", "social"],
    medianSalary: 1500000,
    demand: "low",
    description: "Øverste leder i en organisasjon med ansvar for strategi og drift.",
    educationPaths: ["Variert — økonomi, juss, teknologi + ledererfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 1,
  },
  {
    id: "cmo",
    title: "CMO / Markedssjef",
    sector: "Forretning",
    educationLevel: "master",
    riasecCodes: ["enterprising", "artistic", "social"],
    medianSalary: 980000,
    demand: "medium",
    description: "Ansvarlig for markedsstrategi, merkevare og kommunikasjon.",
    educationPaths: ["Markedsføring/kommunikasjon (master) + erfaring"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "art-director",
    title: "Art Director",
    sector: "Kreativ",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "enterprising", "realistic"],
    medianSalary: 670000,
    demand: "medium",
    description: "Ansvarlig for visuell stil og estetisk retning i reklamebyrå eller mediehus.",
    educationPaths: ["Grafisk design (bachelor) + erfaring"],
    advancesTo: ["creative-director"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "redaktoer",
    title: "Redaktør",
    sector: "Kreativ",
    educationLevel: "bachelor",
    riasecCodes: ["artistic", "enterprising", "social"],
    medianSalary: 700000,
    demand: "low",
    description: "Har det journalistiske og etiske ansvaret for et medium.",
    educationPaths: ["Journalistikk + erfaring som journalist"],
    aiDisruptionRisk: "medium",
    growthTrend: "declining",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "byplanlegger",
    title: "Byplanlegger / Arealplanlegger",
    sector: "Offentlig",
    educationLevel: "master",
    riasecCodes: ["artistic", "investigative", "realistic"],
    medianSalary: 680000,
    demand: "medium",
    description: "Planlegger arealutnyttelse, infrastruktur og byutvikling.",
    educationPaths: ["Byplanlegging (master) — NTNU, UiB"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: true,
    workLifeBalance: 4,
  },
  {
    id: "prosjektleder",
    title: "Prosjektleder",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["enterprising", "conventional", "realistic"],
    medianSalary: 780000,
    demand: "high",
    description: "Planlegger og leder prosjekter innen bygg, IT eller industri.",
    educationPaths: ["Ingeniør + PMP/Prince2-sertifisering"],
    advancesTo: ["cto", "ceo"],
    aiDisruptionRisk: "medium",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "partner-advokatfirma",
    title: "Partner i advokatfirma",
    sector: "Juss",
    educationLevel: "master",
    riasecCodes: ["enterprising", "investigative", "conventional"],
    medianSalary: 1400000,
    demand: "low",
    description: "Medeier og senior rådgiver i advokatfirma med spesialkompetanse.",
    educationPaths: ["Rettsvitenskap + 10+ år erfaring"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 2,
  },
  {
    id: "etterforsker",
    title: "Etterforsker",
    sector: "Offentlig",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 620000,
    demand: "medium",
    description: "Etterforsker straffbare handlinger på vegne av politiet.",
    educationPaths: ["Politihøgskolen + etterforskningseraring"],
    aiDisruptionRisk: "low",
    growthTrend: "stable",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "cpo",
    title: "CPO / Produktdirektør",
    sector: "Teknologi",
    educationLevel: "master",
    riasecCodes: ["enterprising", "investigative", "social"],
    medianSalary: 1100000,
    demand: "medium",
    description: "Overordnet ansvar for produktstrategi og produktportefølje.",
    educationPaths: ["Teknologi/økonomi + erfaring som produktleder"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },

  // ─── Nye karrierer (#115) — Cloud, data, klima, yrkesfag ────────────────
  {
    id: "cloud-arkitekt",
    title: "Cloud-arkitekt",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 850000,
    demand: "high",
    description: "Designer og implementerer skyinfrastruktur — AWS, Azure, GCP. NOK 12,4 mrd marked innen 2029.",
    educationPaths: ["Informatikk (bachelor/master)", "Cloud-sertifiseringer (AWS/Azure/GCP)"],
    advancesTo: ["cto", "tech-lead"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "dataingeniør",
    title: "Dataingeniør",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "conventional"],
    medianSalary: 760000,
    demand: "high",
    description: "Bygger datapipelines, ETL-prosesser og datainfrastruktur for analyse og AI.",
    educationPaths: ["Informatikk/datateknikk (bachelor)", "Data engineering (master)"],
    advancesTo: ["data-scientist", "tech-lead"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },
  {
    id: "klimaanalytiker",
    title: "Klimaanalytiker",
    sector: "Bærekraft",
    educationLevel: "master",
    riasecCodes: ["investigative", "conventional", "realistic"],
    medianSalary: 660000,
    demand: "high",
    description: "Analyserer klimadata, modellerer utslippsscenarier og rådgir om klimatilpasning.",
    educationPaths: ["Klimavitenskap (master)", "Miljøfysikk (NTNU, UiB)", "Geografi + statistikk"],
    advancesTo: ["barekraftskonsulent"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 4,
  },
  {
    id: "energiradgiver",
    title: "Energirådgiver",
    sector: "Energi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "social", "conventional"],
    medianSalary: 620000,
    demand: "high",
    description: "Rådgir bedrifter og kommuner om energieffektivisering, ENØK-tiltak og elektrifisering.",
    educationPaths: ["Energiteknikk (bachelor)", "Miljøteknikk (fagskole/bachelor)"],
    advancesTo: ["energiingenior", "barekraftskonsulent"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 4,
  },
  {
    id: "ai-agent-utvikler",
    title: "AI Agent-utvikler",
    sector: "Teknologi",
    educationLevel: "bachelor",
    riasecCodes: ["investigative", "realistic", "artistic"],
    medianSalary: 830000,
    demand: "high",
    description: "Bygger autonome AI-agenter og automatiseringssystemer. 1 587% vekst i stillinger i 2025.",
    educationPaths: ["Informatikk + AI/ML (bachelor/master)", "Prompt engineering + utviklingserfaring"],
    advancesTo: ["ml-engineer", "ai-researcher"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: false,
    workLifeBalance: 4,
  },

  // ─── Yrkesfag — vokser 3x raskere enn akademiske roller (#115) ──────────
  {
    id: "elektriker",
    title: "Elektriker",
    sector: "Energi",
    educationLevel: "fagbrev",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 530000,
    demand: "high",
    description: "Installerer og vedlikeholder elektriske anlegg. Kritisk for elektrifisering av Norge.",
    educationPaths: ["Elektro VGS → læretid (fagbrev)", "Automatisering VGS"],
    advancesTo: ["energiingenior", "vindkrafttekniker"],
    aiDisruptionRisk: "low",
    growthTrend: "booming",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "roerlegger",
    title: "Rørlegger (VVS)",
    sector: "Energi",
    educationLevel: "fagbrev",
    riasecCodes: ["realistic", "conventional", "investigative"],
    medianSalary: 520000,
    demand: "high",
    description: "Installerer varmepumper, fjernvarme og vannbårne systemer. Sentral i grønt skifte.",
    educationPaths: ["Klima, energi og miljø VGS → læretid", "VVS-fagbrev"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "toemrer",
    title: "Tømrer",
    sector: "Ingeniør",
    educationLevel: "fagbrev",
    riasecCodes: ["realistic", "conventional", "artistic"],
    medianSalary: 500000,
    demand: "high",
    description: "Bygger og rehabiliterer bygninger — økende etterspørsel pga. grønt skifte og bærekraftig bygg.",
    educationPaths: ["Bygg og anlegg VGS → læretid (fagbrev)", "Tømrermester (videreutdanning)"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: true,
    workLifeBalance: 3,
  },
  {
    id: "helsefagarbeider",
    title: "Helsefagarbeider",
    sector: "Helse",
    educationLevel: "fagbrev",
    riasecCodes: ["social", "realistic", "conventional"],
    medianSalary: 440000,
    demand: "high",
    description: "Grunnleggende pleie og omsorg — vedvarende mangel i Norge.",
    educationPaths: ["Helse og oppvekst VGS → læretid (fagbrev)"],
    advancesTo: ["sykepleier"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
  {
    id: "automatiker",
    title: "Automatiker / Industrimekaniker",
    sector: "Teknologi",
    educationLevel: "fagbrev",
    riasecCodes: ["realistic", "investigative", "conventional"],
    medianSalary: 560000,
    demand: "high",
    description: "Programmerer og vedlikeholder industrielle styresystemer og roboter.",
    educationPaths: ["Automatisering VGS → læretid", "Industrimekaniker (fagbrev)"],
    advancesTo: ["robotikkingenior"],
    aiDisruptionRisk: "low",
    growthTrend: "growing",
    sustainability: false,
    workLifeBalance: 3,
  },
];

// ---------------------------------------------------------------------------
// Sektorer og farger
// ---------------------------------------------------------------------------

export const SECTOR_COLORS: Record<string, string> = {
  Teknologi:    "bg-blue-500/15 border-blue-500/30 text-blue-700 dark:text-blue-300",
  Helse:        "bg-red-500/15 border-red-500/30 text-red-700 dark:text-red-300",
  Utdanning:    "bg-amber-500/15 border-amber-500/30 text-amber-700 dark:text-amber-300",
  Økonomi:      "bg-green-500/15 border-green-500/30 text-green-700 dark:text-green-300",
  Forretning:   "bg-orange-500/15 border-orange-500/30 text-orange-700 dark:text-orange-300",
  Kreativ:      "bg-violet-500/15 border-violet-500/30 text-violet-700 dark:text-violet-300",
  Ingeniør:     "bg-slate-500/15 border-slate-500/30 text-slate-700 dark:text-slate-300",
  Naturvitenskap: "bg-teal-500/15 border-teal-500/30 text-teal-700 dark:text-teal-300",
  Juss:         "bg-indigo-500/15 border-indigo-500/30 text-indigo-700 dark:text-indigo-300",
  Sosial:       "bg-pink-500/15 border-pink-500/30 text-pink-700 dark:text-pink-300",
  Offentlig:    "bg-cyan-500/15 border-cyan-500/30 text-cyan-700 dark:text-cyan-300",
  Akademia:     "bg-fuchsia-500/15 border-fuchsia-500/30 text-fuchsia-700 dark:text-fuchsia-300",
  Ledelse:      "bg-rose-500/15 border-rose-500/30 text-rose-700 dark:text-rose-300",
  Energi:       "bg-yellow-500/15 border-yellow-500/30 text-yellow-700 dark:text-yellow-300",
  Bærekraft:    "bg-emerald-500/15 border-emerald-500/30 text-emerald-700 dark:text-emerald-300",
};

// ---------------------------------------------------------------------------
// Fit-score beregning (0–100)
// ---------------------------------------------------------------------------

export function calcFitScore(
  career: CareerNode,
  riasec: RiasecScores
): number {
  if (!riasec) return 50;
  const topCodes = career.riasecCodes;
  const total = topCodes.reduce((sum, code) => sum + (riasec[code] ?? 50), 0);
  return Math.round(total / topCodes.length);
}

export function fitScoreColor(score: number): string {
  if (score >= 70) return "text-green-600 dark:text-green-400";
  if (score >= 45) return "text-amber-600 dark:text-amber-400";
  return "text-muted-foreground";
}

export function fitScoreBg(score: number): string {
  if (score >= 70) return "border-green-500/40 bg-green-500/5";
  if (score >= 45) return "border-amber-500/30 bg-amber-500/5";
  return "border-border bg-muted/20 opacity-60";
}

export type EducationLevelLabel = Record<EducationLevel, string>;

export const EDU_LABELS: EducationLevelLabel = {
  vgs: "VGS",
  fagbrev: "Fagbrev",
  bachelor: "Bachelor",
  master: "Master",
  phd: "PhD / Doktorgrad",
};

export const DEMAND_LABELS: Record<Demand, string> = {
  high: "Høy etterspørsel",
  medium: "Moderat etterspørsel",
  low: "Lavere etterspørsel",
};

// ---------------------------------------------------------------------------
// AI-disrupsjon og veksttrend (#115)
// ---------------------------------------------------------------------------

export const AI_RISK_LABELS: Record<AiDisruptionRisk, string> = {
  low: "Lav AI-risiko",
  medium: "Moderat AI-risiko",
  high: "Høy AI-risiko",
};

export const AI_RISK_COLORS: Record<AiDisruptionRisk, string> = {
  low: "text-green-600 dark:text-green-400",
  medium: "text-amber-600 dark:text-amber-400",
  high: "text-red-600 dark:text-red-400",
};

export const GROWTH_TREND_LABELS: Record<GrowthTrend, string> = {
  declining: "Synkende",
  stable: "Stabil",
  growing: "Voksende",
  booming: "Sterk vekst",
};

export const GROWTH_TREND_ICONS: Record<GrowthTrend, string> = {
  declining: "↓",
  stable: "→",
  growing: "↑",
  booming: "↑↑",
};

export const GROWTH_TREND_COLORS: Record<GrowthTrend, string> = {
  declining: "text-red-600 dark:text-red-400",
  stable: "text-muted-foreground",
  growing: "text-green-600 dark:text-green-400",
  booming: "text-emerald-600 dark:text-emerald-400",
};
